# Generated by Django 4.1.2 on 2023-12-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='age',
            field=models.IntegerField(),
        ),
    ]
